language: r
distro: xenial  # binary packages
sudo: true      # dito
cache: packages
branches:
  only:
  - master

r:
- oldrel
- release
- devel

r_binary_packages:
# Additional packages for tests...
- roxygen2
- devtools

addons:
  apt:
    packages:
    # Install the headers for the Cairo package.
    - libcairo2-dev
    - libjpeg-dev

script:
- R CMD build .
- R CMD check IRdisplay*.tar.gz --as-cran
- cat "/home/travis/build/IRkernel/IRdisplay/IRdisplay.Rcheck/00check.log"
- grep -q -R 'WARNING' "/home/travis/build/IRkernel/IRdisplay/IRdisplay.Rcheck/00check.log" ; [ $? -ne 0 ]
- grep -q -R 'NOTE' "/home/travis/build/IRkernel/IRdisplay/IRdisplay.Rcheck/00check.log"; [ $? -ne 0 ]
- Rscript -e 'devtools::test(reporter="check")'
